// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  all: string;
  appear: string;
  cloud: string;
  inspiration: string;
  light: string;
  rain: string;
  "title-appear": string;
  "weather-icon-move": string;
  weatherCard: string;
  weatherIconCloud: string;
  weatherIconSun: string;
  weatherWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
